name: CI Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Simulate Build
        run: echo "Building..."
      - name: Simulate Test
        run: echo "Testing..."
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-artifact
          path: README.md
        
