name: CI Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Example setup steps (modify per your project)
      - name: Simulate Build
        run: echo "Building..."

      - name: Simulate Test
        run: echo "Testing..."

      # Updated artifact upload to v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifact
          path: README.md
